version: '3.0'
services:
  app:
    container_name: app
    build: ./
    environment:
      HOST: db
      DATABASE: Capsule
    ports:
      - 5000:5000
    depends_on:
      - 'mongo'
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
